### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by ghost** [MakeWorkSimple/sync_gitee#15]
就是加入用vscode1.0同步到码云后，假如换了电脑后下载的vscode为2.0后，那么会导致vscode无法正确加载插件无法使用。可能我是特例，在此多谢作者。

**Comment by bufubaoni** [comment]
@ljh101
不能正常加载的原因是因为官方 一个文件extension.json 文件和之前版本生成的文件重名，所以无法加载。然后进入到文件删掉此文件即可，之后版本不会再生成此文件。
