### ISSUE TITLE
下载之后不能自动恢复

### ISSUE THREAD

**Issue by undercake** [MakeWorkSimple/sync_gitee#3]
下载备份的配置文件之后不能自动恢复

**Comment by bufubaoni** [comment]
安装插件会在后台静默进行
其他配置文件会立即生效
如果关闭主进程 需要重新执行 dowload 命令，会看到已经安装的插件，此时会安装没有安装完的插件

**Comment by undercake** [comment]
执行了download命令之后看到有下载成功，但是等了两个小时一个插件也没装上，试了一下，vscode其他插件能正常安装

**Comment by bufubaoni** [comment]
插件版本是 0.1.7 吗？最早的一版不能同步插件，最新一版本已经修复了。

**Comment by bufubaoni** [comment]
我已经找到问题所在了，由于本地文件存在，导致配置文件读取错误，稍后fix，感谢反馈。

**Comment by undercake** [comment]
没关系的，大家共同进步嘛
