### ISSUE TITLE
不知道为什么这个插件经常上传失败

### ISSUE THREAD

**Issue by BeginsDuang** [MakeWorkSimple/sync_gitee#7]
输出了信息
但是网页上查看，前一天推送的，第二天都没上传上去，还是显示好久之前的更新

**Comment by BeginsDuang** [comment]
> 输出了信息
> 但是网页上查看，前一天推送的，第二天都没上传上去，还是显示好久之前的更新

**Comment by BeginsDuang** [comment]
好吧，多次测试了，确实传上去了，但是网页显示时间不会更新，这个就蛋疼了

**Comment by bufubaoni** [comment]
> 好吧，多次测试了，确实传上去了，但是网页显示时间不会更新，这个就蛋疼了

添加了一个sync.lock可以看到当前gist最后一次上传的时间。
将上传如果失败，输出error， 如果网络不好确实会出现上传失败的情况，当然如果网络好我这里也出现过失败，显示地址不存在。
